language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'sailor-module-user' ]; then cd .. && eval "mv $currentfolder sailor-module-user" && cd sailor-module-user; fi
